### PR TITLE
Upload of cover image and audio.

### PR DESCRIPTION
**Pull request by Matlawton**
@kienstra 
Please view the image and audio file attached.
The audio is to be played on a loop in the background and the cover image is to be overlayed on the game, one click of the cover image will launch the game.

### CODE REVIEW

**Comment by kienstra** [comment]
Nice, thanks for opening this. I'll look at it soon.

**Comment by kienstra** [comment]
Hi @Matlawton,
It looks like the `img` isn't added to the DOM [here](https://github.com/Matlawton/table-tennis/blob/5eee1aabde85b8af5261365d415c8dbe820ee1d4/index.html#L45-L48), though you'd think that would work.

With this, it's in the DOM:

```diff
diff --git a/index.html b/index.html
index b661c79..50370dc 100644
--- a/index.html
+++ b/index.html
@@ -3,12 +3,12 @@
                 function GFG_Fun() {
-            var img = document.createElement('img');
-            img.src = 'cover.png';
-            document.getElementById('body').appendChild(img);

+        <img id="start-game" src="cover.png" />
     </body>
 

```

But it's still appearing below the game:

ibaosdifsabdfsa

It'd probably be good to only render the game when they have clicked the image.

**Comment by kienstra** [comment]
In the diff shown above, the red lines are for deletions, and the green line is for addition.

The green line should go inside the `<body>` tag:

```html
<img src="cover.png" />
```

**Comment by kienstra** [comment]
Hi @Matlawton,
A few ideas:

1. The `` could instead be a `<button>`, to be more accessible:

```html
        <button id="start-game" style="background-image: url('cover.png')" />
    </body>
```
2. It could have a `background-image` of the image, though you'll have to make the button bigger so it's visible
3. The `window.onload` [callback](https://github.com/Matlawton/table-tennis/blob/5eee1aabde85b8af5261365d415c8dbe820ee1d4/index.html#L61-L76) could have a listener for that button being clicked:

```js
            window.onload = function() {
                document.querySelector( '#start-game' ).addEventListener(
                    'click',
                    function() {
                        canvas = document.getElementById('gameCanvas');
                        canvas.style = 'display: block';
                        canvasContext = canvas.getContext('2d');

                        var framesPerSecond = 30;
                        setInterval(function() {
                        moveEverything();
                        drawEverything();
                        }, 1000/framesPerSecond);

                        canvas.addEventListener('mousedown', handleMouseClick);

                        canvas.addEventListener('mousemove',
                            function(evt) {
                                var mousePos = calculateMousePos(evt);
                                paddle1Y = mousePos.y-(PADDLE_HEIGHT/2);
                            });
                    });
                 }
```

4. On line 12, the `<canvas>` could have an inline style of `display:none` so that it only displays when the 'Start' button is clicked:

```html
<canvas style="display: none" id="gameCanvas" width="800" height="600"></canvas>
```

the-start-button

**Comment by Matlawton** [comment]
Hey @kienstra I tried these locally and it did not seem to work nicely for me, instead, the game itself seemed to vanish completely.

**Pull request closed without merging**
